
package br.com.nivlabs.cliniv.enums;

/**
 * Segmentações de cobertura de planos de saúde
 * 
 * @author viniciosarodrigues
 *
 */
public enum Segmentation {

	// AMBULATORIAL
	AMBULATORIAL,
	// HOSPITALAR SEM OBSTETRÍCIA
	HOSPITAL_WITHOUT_OBSTETRICS,
	// HOSPITALAR COM OBSTETRÍCIA
	HOSPITAL_WITH_OBSTETRICS,
	// ODONTOLÓGICO
	EXCLUSIVELY_DENTISTRY,
	// REFERÊNCI
	REFERENCE,
	// AMBULATORIAL + ODONTOLÓGICO
	AMBULATORIAL_AND_DENTISTRY,
	// AMBULATORIAL + HOSPITALAR SEM OBSTETRÍCIA
	AMBULATORIAL_AND_HOSPITAL_WITHOUT_OBSTETRICS,
	// AMBULATORIAL + HOSPITALR COM OBSTETRÍCIA
	AMBULATORIAL_AND_HOSPITAL_WITH_OBSTETRICS,
	// HOSPITALAR COM OBSTETRÍCIA + ODONTOLOGIA
	HOSPITAL_WITH_OBSTETRICS_AND_DENTISTRY,
	// HOSPITALAR SEM OBSTETRÍCIA + DENTISTA
	HOSPITAL_WITHOUT_OBSTETRICS_AND_DENTISTRY,
	// AMBULATORIAL + HOSPITALAR SEM OBSTETRÍCIA + DENTISTA
	AMBULATORIAL_AND_HOSPITAL_WITHOUT_OBSTETRICS_AND_DENTISTRY,
	// AMBULATORIAL + HOSPITALAR COM OBSTETRÍCIA + DENTISTA
	AMBULATORIAL_AND_HOSPITAL_WITH_OBSTETRICS_AND_DENTISTRY
}
