
package br.com.nivlabs.gp.enums;

/**
 * Segmentações de cobertura de planos de saúde
 * 
 * @author viniciosarodrigues
 *
 */
public enum Segmentation {
    AMBULATORIAL,
    HOSPITAL_WITHOUT_OBSTETRICS,
    HOSPITAL_WITH_OBSTETRICS,
    EXCLUSIVELY_DENTISTRY,
    REFERENCE,
    AMBULATORIAL_AND_DENTISTRY,
    AMBULATORIAL_AND_HOSPITAL_WITHOUT_OBSTETRICS,
    AMBULATORIAL_AND_HOSPITAL_WITH_OBSTETRICS,
    HOSPITAL_WITH_OBSTETRICS_AND_DENTISTRY,
    HOSPITAL_WITHOUT_OBSTETRICS_AND_DENTISTRY,
    AMBULATORIAL_AND_HOSPITAL_WITHOUT_OBSTETRICS_AND_DENTISTRY,
    AMBULATORIAL_AND_HOSPITAL_WITH_OBSTETRICS_AND_DENTISTRY
}
