CREATE TABLE `DOCUMENTO_DIGITAL` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(45) NOT NULL,
  `BASE64` LONGBLOB NOT NULL,
  `DOC_NAME` VARCHAR(80) NOT NULL,
  `DATA_CRIACAO` DATE NOT NULL,
  PRIMARY KEY (`ID`));
