ALTER TABLE `DOCUMENTO_PESSOA` 
ADD COLUMN `EXPEDIDOR` VARCHAR(100) NULL AFTER `VALOR`,
ADD COLUMN `DATA_EXPEDICAO` DATE NULL AFTER `EXPEDIDOR`,
ADD COLUMN `VALIDADE` DATE NULL AFTER `DATA_EXPEDICAO`,
ADD COLUMN `UF_EXPEDICAO` VARCHAR(45) NULL AFTER `VALIDADE`;
