ALTER TABLE `ANAMNESE_ITEM` 
ADD INDEX `FK_ANAMNESE_IT_FORM_idx` (`ID_ANAMNESE_FORM` ASC);
;
ALTER TABLE `ANAMNESE_ITEM` 
ADD CONSTRAINT `FK_ANAMNESE_IT_FORM`
  FOREIGN KEY (`ID_ANAMNESE_FORM`)
  REFERENCES `ANAMNESE_FORM` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
