INSERT INTO ESPECIALIDADE (nome) VALUES ("Acupuntura");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Alergia e Imunologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Anestesiologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Angiologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cancerologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cardiologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Cardivascular");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia da Mão");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia de Cabeça e Pescoço");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia do Aparelho Digestivo");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Geral");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Pediátrica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Plástica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Torácica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Cirurgia Vascular");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Clínica Médica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Coloproctologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Dermatologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Endocrinologia e Metabologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Endoscopia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Gastroenterologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Genética Médica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Geriatria");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Ginecologia e Obstetrícia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Hematologia e Hemoterapia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Homeopatia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Infectologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Mastologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina de Família e Comunidade");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina do Trabalho");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina de Tráfego");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Esportiva");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Física e Reabilitação");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Intensiva");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Legal e Perícia Médica");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Nuclear");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Medicina Preventiva e Social");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Nefrologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Neurocirurgia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Neurologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Nutrologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Oftalmologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Ortopedia e Traumatologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Otorrinolaringologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Patologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Patologia Clínica/Medicina Laboratorial");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Pediatria");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Pneumologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Psiquiatria");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Radiologia e Diagnóstico por Imagem");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Radioterapia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Reumatologia");
INSERT INTO ESPECIALIDADE (nome) VALUES ("Urologia");