ALTER TABLE `VISITA_EVENTO` 
DROP FOREIGN KEY `fk_VISITA_RESP`;
ALTER TABLE `VISITA_EVENTO` 
CHANGE COLUMN `ID_RESPONSAVEL` `ID_RESPONSAVEL` BIGINT(20) NULL ;
ALTER TABLE `VISITA_EVENTO` 
ADD CONSTRAINT `fk_VISITA_RESP`
  FOREIGN KEY (`ID_RESPONSAVEL`)
  REFERENCES `RESPONSAVEL` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;