ALTER TABLE `VISITA_EVENTO` 
ADD UNIQUE INDEX `ID_DOCUMENTO_DIGITAL_UNIQUE` (`ID_DOCUMENTO_DIGITAL` ASC);
ALTER TABLE `VISITA_EVENTO` 
ADD CONSTRAINT `fk_VISITA_DOC_DIGITAL`
  FOREIGN KEY (`ID_DOCUMENTO_DIGITAL`)
  REFERENCES `DOCUMENTO_DIGITAL` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
