ALTER TABLE APP_PARAM ADD ALIAS varchar(100) NULL;

UPDATE APP_PARAM SET ALIAS = 'ENABLE_SEARCH_BY_ZIP_CODE' WHERE ID = 1;
UPDATE APP_PARAM SET ALIAS = 'ZIP_CODE_SEARCH_PROVIDER' WHERE ID = 2;

UPDATE APP_PARAM SET ALIAS = 'AGENDA_OPENING_TIME' WHERE ID = 3;
UPDATE APP_PARAM SET NOME = 'Hora de abertura da agenda' WHERE ID = 3;
UPDATE APP_PARAM SET GRUPO = 'AGENDA' WHERE ID = 3;
UPDATE APP_PARAM SET TIPO = 'STRING' WHERE ID = 3;


UPDATE APP_PARAM SET ALIAS = 'AGENDA_CLOSING_TIME' WHERE ID = 4;
UPDATE APP_PARAM SET NOME = 'Hora de encerramento da agenda' WHERE ID = 4;
UPDATE APP_PARAM SET GRUPO = 'AGENDA' WHERE ID = 4;
UPDATE APP_PARAM SET TIPO = 'STRING' WHERE ID = 4;



UPDATE APP_PARAM SET ALIAS = 'BREAK_TIME_BETWEEN_SCHEDULE_TIMES' WHERE ID = 5;
UPDATE APP_PARAM SET NOME = 'Intervalos entre horários da agenda' WHERE ID = 5;
UPDATE APP_PARAM SET GRUPO = 'AGENDA' WHERE ID = 5;
UPDATE APP_PARAM SET TIPO = 'NUMBER' WHERE ID = 5;

ALTER TABLE APP_PARAM MODIFY ALIAS varchar(100) NOT NULL AFTER ID;

INSERT
	INTO
	APP_PARAM (ID,
	ALIAS,
	NOME,
	GRUPO,
	TIPO,
	VALOR)
VALUES (6,
'BLOCK_OUT_OF_SCHEDULE_APPOINTMENT',
'Bloquear agendamento fora do horário',
'AGENDA',
'BOOL',
'false');

INSERT
	INTO
	APP_PARAM (ID,
	ALIAS,
	NOME,
	GRUPO,
	TIPO,
	VALOR)
VALUES (7,
'BLOCKS_READING_THE_MEDICAL_RECORD_WITHOUT_ACTIVE_SERVICE',
'Bloquear leitura de prontuário sem atendimento ativo',
'ATENDIMENTO',
'BOOL',
'true');

INSERT
	INTO
	APP_PARAM (ID,
	ALIAS,
	NOME,
	GRUPO,
	TIPO,
	VALOR)
VALUES (8,
'ENABLE_SERVICE_SHARING',
'Compartilhar atendimentos entre profissionais',
'ATENDIMENTO',
'BOOL',
'false');


CREATE UNIQUE INDEX APP_PARAM_ALIAS_UK USING BTREE ON APP_PARAM (ALIAS);
