CREATE TABLE `PACIENTE_ALERGIA` (
  `ID` BIGINT(20) NOT NULL,
  `PACIENTE_ID` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PACIENTE_ALERGIA_PACIENTE_idx` (`PACIENTE_ID` ASC),
  CONSTRAINT `FK_PACIENTE_ALERGIA_PACIENTE`
    FOREIGN KEY (`PACIENTE_ID`)
    REFERENCES `PACIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
