CREATE TABLE `FORMULARIO_RESPONDIDO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` BIGINT(20) NOT NULL,
  `ID_VISITA` BIGINT(20) NOT NULL,
  `QUESTAO` VARCHAR(4000) NOT NULL,
  `RESPOSTA` VARCHAR(4000) NOT NULL,
  PRIMARY KEY (`ID`));
