UPDATE INSTITUTO 
	SET 
		`CNPJ` = '68825375000124',
		`NOME` = 'NIV LABS',
		`NOME_CORPORATIVO` = 'NIV LABS',
		`LOGO` = NULL,
		`LOGRADOURO` = 'NÃO INFORMADO',
		`CEP` = '11123123',
		`ESTADO` = 'PE',
		`BAIRRO` = 'BOA VIAGEM',
		`CIDADE` = 'RECIFE',
		`TELEFONE` = '8112341234',
		`DEPENDENCIA` = 'NÃO INFORMADO',
		`GESTOR` = 'NÃO INFORMADO',
		`TELEFONE_GESTOR` ='81112341234',
		`EMAIL_GESTOR` = 'atendimento@nivlabs.com.br'
WHERE `NOME` LIKE '%Georgia%';