CREATE TABLE `TELEFONE` (
  `ID_PESSOA` bigint(20) NOT NULL,
  `TELEFONE` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_PESSOA`),
  UNIQUE KEY `TELEFONE_UNIQUE` (`TELEFONE`),
  CONSTRAINT `FK_TELEFONE_PACIENTE` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PACIENTE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
