CREATE TABLE `EVOLUCAO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_VISITA` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(600) NOT NULL,
  `DH_EVOLUCAO` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_EVOLUCAO_VISITA`
    FOREIGN KEY (`ID_VISITA`)
    REFERENCES `VISITA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);