ALTER TABLE `PACIENTE` 
ADD COLUMN `TIPO_PACIENTE` VARCHAR(15) NULL AFTER `CODIGO_SUS`,
ADD COLUMN `ANOTACOES` VARCHAR(300) NULL AFTER `TIPO_PACIENTE`;

UPDATE `PACIENTE` SET `TIPO_PACIENTE` = 'IDENTIFIED';

ALTER TABLE `PACIENTE` MODIFY `TIPO_PACIENTE` VARCHAR(15) NOT NULL;
