ALTER TABLE `devdb`.`TELEFONE` 
DROP FOREIGN KEY `FK_TELEFONE_PACIENTE`;
ALTER TABLE `devdb`.`TELEFONE` 
CHANGE COLUMN `ID_PESSOA` `ID_PACIENTE` BIGINT(20) NOT NULL ;
ALTER TABLE `devdb`.`TELEFONE` 
ADD CONSTRAINT `FK_TELEFONE_PACIENTE`
  FOREIGN KEY (`ID_PACIENTE`)
  REFERENCES `devdb`.`PACIENTE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
