TRUNCATE `INSTITUTO`;

ALTER TABLE `INSTITUTO` 
ADD COLUMN `CHAVE_ACESSO` VARCHAR(80) NOT NULL AFTER `USUARIO_DE_REGISTRO`,
ADD COLUMN `DATA_INICIO` DATETIME NULL AFTER `CHAVE_ACESSO`,
ADD COLUMN `DATA_FIM` DATETIME  NULL AFTER `DATA_INICIO`,
ADD UNIQUE INDEX `CHAVE_ACESSO_UNIQUE` (`CHAVE_ACESSO` ASC);
