-- Copiando estrutura para tabela LAYOUT_RELATORIO
CREATE TABLE `LAYOUT_RELATORIO` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(200) NOT NULL,
	`DESCRICAO` VARCHAR(200) NOT NULL,
	`XML` longblob DEFAULT NULL,
	`DATA` DATE NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

-- Copiando estrutura para tabela PARAMETROS_LAYOUT_RELATORIO
CREATE TABLE `PARAMETROS_LAYOUT_RELATORIO` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ID_LAYOUT_RELATORIO` BIGINT(20) NOT NULL,
	`NOME` VARCHAR(200) NOT NULL,
	`TIPO` VARCHAR(200) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_LAYOUT` (`ID_LAYOUT_RELATORIO`),
	CONSTRAINT `FK_LAYOUT` FOREIGN KEY (`ID_LAYOUT_RELATORIO`) REFERENCES `LAYOUT_RELATORIO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;