CREATE TABLE `TEMPLATE_DOC` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(200) NOT NULL,
  `TEXTO_TEMPLATE` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`, `ID_USUARIO`));

ALTER TABLE `TEMPLATE_DOC`
ADD CONSTRAINT `FK_TEMPLATE_USUARIO`
FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO`(`ID`);