ALTER TABLE `VISITA` 
CHANGE COLUMN `SETOR_ATUAL` `ACOMODACAO_ATUAL` BIGINT(20) NOT NULL ,
ADD INDEX `FK_VISITA_ACOMOD_idx` (`ACOMODACAO_ATUAL` ASC);
;
ALTER TABLE `VISITA` 
ADD CONSTRAINT `FK_VISITA_ACOMOD`
  FOREIGN KEY (`ACOMODACAO_ATUAL`)
  REFERENCES `SALA_LEITO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
