ALTER TABLE `TELEFONE` 
DROP FOREIGN KEY `FK_TELEFONE_PACIENTE`;
ALTER TABLE `TELEFONE` 
CHANGE COLUMN `ID_PESSOA` `ID_PACIENTE` BIGINT(20) NOT NULL ;
ALTER TABLE `TELEFONE` 
ADD CONSTRAINT `FK_TELEFONE_PACIENTE`
  FOREIGN KEY (`ID_PACIENTE`)
  REFERENCES `PACIENTE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
