UPDATE ANAMNESE_ITEM SET TIPO = 'PASSWORD' where TIPO = 'password';
UPDATE ANAMNESE_ITEM SET TIPO = 'STRING' where TIPO = 'string';
UPDATE ANAMNESE_ITEM SET TIPO = 'BOOL' where TIPO = 'bool';
UPDATE ANAMNESE_ITEM SET TIPO = 'GROUP' where TIPO = 'group';
UPDATE ANAMNESE_ITEM SET TIPO = 'NUMBER' where TIPO = 'number';