ALTER TABLE `PACIENTE` 
ADD COLUMN `DATA_CRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `RESPONSAVEL`
ADD COLUMN `DATA_CRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `USUARIO` 
ADD COLUMN `DATA_CRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `SETOR` 
ADD COLUMN `DATA_CRIACAO` DATETIME DEFAULT CURRENT_TIMESTAMP;
