ALTER TABLE `PACIENTE` MODIFY `DATA_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `RESPONSAVEL` MODIFY `DATA_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `USUARIO` MODIFY `DATA_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `SETOR` MODIFY `DATA_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;