DROP TABLE IF EXISTS `SETOR`;

CREATE TABLE `SETOR` 
(
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  `ID_SETOR` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SETOR_ID_IDX` (`ID`) USING BTREE,
  KEY `fk_SETOR_SETOR` (`ID_SETOR`),
  CONSTRAINT `fk_SETOR_SETOR` FOREIGN KEY (`ID_SETOR`) REFERENCES `SETOR` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

ALTER TABLE VISITA_EVENTO ADD ID_SETOR BIGINT(20) NULL;

ALTER TABLE VISITA_EVENTO ADD CONSTRAINT fk_VISITA_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
