CREATE TABLE `PROCEDIMENTO` (
  `ID` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  `ATIVO`INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC));  	

  