ALTER TABLE `ANAMNESE` 
DROP FOREIGN KEY `fk_ANAMNESE_ITEM`;
ALTER TABLE `ANAMNESE` 
DROP COLUMN `ID_ANAMNESE_ITEM`,
CHANGE COLUMN `RESPOSTA` `RESPOSTA` VARCHAR(200) NOT NULL ,
ADD COLUMN `PERGUNTA` VARCHAR(400) NOT NULL AFTER `RESPOSTA`,
DROP INDEX `UK_PACITENTE` ;
