ALTER TABLE ANAMNESE DROP FOREIGN  KEY IF EXISTS fk_ANAMNESE_PACIENT;
ALTER TABLE `ANAMNESE` 
DROP COLUMN `ID_PACIENTE`,
DROP INDEX `UK_PACITENTE` ,
ADD UNIQUE INDEX `UK_PACITENTE` (`ID_ANAMNESE_ITEM` ASC, `ID_VISITA` ASC, `ID` ASC),
DROP INDEX `fk_ANAMNESE_PACIENT_idx` ;

ALTER TABLE ANAMNESE_ITEM DROP COLUMN SIM_NAO;
ALTER TABLE ANAMNESE_ITEM ADD TIPO varchar(45) DEFAULT 'string' NOT NULL;
