ALTER TABLE `SETOR` DROP FOREIGN KEY `fk_SETOR_SETOR`;
ALTER TABLE `SETOR` DROP INDEX `fk_SETOR_SETOR`;
ALTER TABLE `SETOR` DROP COLUMN `ID_SETOR`;

CREATE TABLE `SALA_LEITO` (
	`ID` BIGINT(20) AUTO_INCREMENT NOT NULL,
	`NOME` varchar(120) NOT NULL,
	`TIPO` varchar(20) DEFAULT 'ROOM' NOT NULL,
	`SECTOR_ID` BIGINT(20) NOT NULL,
	CONSTRAINT `SALA_LEITO_PK` PRIMARY KEY (`ID`),
	CONSTRAINT `SALA_LEITO_FK` FOREIGN KEY (`SECTOR_ID`) REFERENCES `SETOR`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE
)
COMMENT='Tabela referente a uma sala de atendimento ambulatorial ou leito';
