ALTER TABLE `VISITA_EVENTO` 
DROP FOREIGN KEY `fk_VISITA_SETOR`;
ALTER TABLE `VISITA_EVENTO` 
CHANGE COLUMN `ID_SETOR` `ID_SALA_LEITO` BIGINT(20) NOT NULL ,
ADD INDEX `fk_VISITA_SALA_LEITO_idx` (`ID_SALA_LEITO` ASC),
DROP INDEX `fk_VISITA_SETOR` ;
ALTER TABLE `VISITA_EVENTO` 
ADD CONSTRAINT `fk_VISITA_SALA_LEITO`
  FOREIGN KEY (`ID_SALA_LEITO`)
  REFERENCES `SALA_LEITO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
