ALTER TABLE `DOCUMENTO_DIGITAL` 
CHANGE COLUMN `TYPE` `TIPO` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL ;

ALTER TABLE `DOCUMENTO_DIGITAL` 
CHANGE COLUMN `DOC_NAME` `NOME` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL ;
