CREATE TABLE `ANAMNESE_FORM` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO `ANAMNESE_FORM` VALUES(1, 'ANAMNESE PADRÃO');

ALTER TABLE `ANAMNESE_ITEM` 
ADD COLUMN `ID_ANAMNESE_FORM` BIGINT(20) NULL AFTER `TIPO`;

UPDATE `ANAMNESE_ITEM`
SET `ID_ANAMNESE_FORM`= 1;

ALTER TABLE `ANAMNESE_ITEM` 
CHANGE COLUMN `ID_ANAMNESE_FORM` `ID_ANAMNESE_FORM` BIGINT(20) NOT NULL;
