ALTER TABLE `PESSOA_FISICA` 
ADD COLUMN `GRUPO_ETNICO` VARCHAR(45) NULL AFTER `EMAIL`,
ADD COLUMN `TIPO_SANGUINEO` VARCHAR(45) NULL AFTER `GRUPO_ETNICO`,
ADD COLUMN `NACIONALIDADE` VARCHAR(100) NULL AFTER `TIPO_SANGUINEO`;
