CREATE TABLE `ITEM_PRESCRICAO` (
	`SEQUENCIAL` INT(11) NOT NULL,
	`ID_PRESCRICAO` BIGINT(20) NOT NULL,
	`DESCRICAO` VARCHAR(200) NOT NULL,
	`OBSERVACOES` VARCHAR(200) NULL,
	`VIA_ADM` VARCHAR(100) NULL,
	`DOSAGEM` DECIMAL(10,2) NULL,
	`ID_UNIDADE_MEDIDA` BIGINT(20) NULL,
	`INTERVALO` INT(11) NOT NULL,
	`TIPO_INTERVALO` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`SEQUENCIAL`, `ID_PRESCRICAO`) USING BTREE,
	CONSTRAINT `FK_ITEMPRESC_PRESC`FOREIGN KEY (`ID_PRESCRICAO`) REFERENCES `PRESCRICAO` (`ID`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `FK_ITEMPRESC_UNIMED`FOREIGN KEY (`ID_UNIDADE_MEDIDA`) REFERENCES `UNIDADE_MEDIDA` (`ID`) ON UPDATE RESTRICT ON DELETE RESTRICT
);