UPDATE INSTITUTO 
	SET 
		`CNPJ` = '68825375000124' AND
		`NOME` = 'NIV LABS' AND
		`NOME_CORPORATIVO` = 'NIV LABS' AND
		`LOGO` = NULL AND
		`LOGRADOURO` = 'NÃO INFORMADO' AND
		`CEP` = '11123123' AND
		`ESTADO` = 'PE' AND
		`BAIRRO` = 'BOA VIAGEM' AND
		`CIDADE` = 'RECIFE' AND
		`TELEFONE` = '8112341234' AND
		`DEPENDENCIA` = 'NÃO INFORMADO' AND
		`GESTOR` = 'NÃO INFORMADO' AND
		`TELEFONE_GESTOR` ='81112341234' AND
		`EMAIL_GESTOR` = 'atendimento@nivlabs.com.br'
WHERE `NOME` LIKE '%Georgia%';
