CREATE TABLE `NIV_PRE_CLIENTE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NOME_CLINICA` VARCHAR(200) NOT NULL,
  `NOME_GESTOR` VARCHAR(200) NOT NULL,
  `TIPO_CGC` VARCHAR(4) NOT NULL,
  `CGC` VARCHAR(16) NOT NULL,
  `EMAIL` VARCHAR(200) NOT NULL,
  `TELEFONE_PRINCIPAL` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`));
