ALTER TABLE `PROCEDIMENTO` 
ADD COLUMN `VALOR_BASE` DECIMAL(20,0) NULL AFTER `ATIVO`,
ADD COLUMN `PERIOCIDADE` VARCHAR(45) NULL AFTER `VALOR_BASE`,
ADD COLUMN `REQ_AUTORIZACAO_ESPECIAL` INT(1) NULL DEFAULT 0 AFTER `PERIOCIDADE`,
ADD COLUMN `REQ_AUDIT_PREV` INT(1) NULL DEFAULT 0 AFTER `REQ_AUTORIZACAO_ESPECIAL`,
ADD COLUMN `REQ_ESPECIALIDADE` INT(1) NULL DEFAULT 0 AFTER `REQ_AUDIT_PREV`,
ADD COLUMN `IDADE_MAX` VARCHAR(45) NULL AFTER `REQ_ESPECIALIDADE`;
