CREATE TABLE `LAYOUT_RELATORIO` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`NOME` VARCHAR(200) NOT NULL,
	`DESCRICAO` VARCHAR(200) NOT NULL,
	`DATA` DATE NOT NULL,
	`SQL` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`id`)
);
#
CREATE TABLE `PARAMETROS_LAYOUT_RELATORIO` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`COD_LAYOUT_RELATORIO` BIGINT(20) NOT NULL,
	`NOME` VARCHAR(200) NOT NULL,
	`LABEL` VARCHAR(200) NOT NULL,
	`TIPO` VARCHAR(200) NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `FK_LAYOUT` (`COD_LAYOUT_RELATORIO`),
	CONSTRAINT `FK_LAYOUT` FOREIGN KEY (`COD_LAYOUT_RELATORIO`) REFERENCES `LAYOUT_RELATORIO` (`id`)  ON DELETE NO ACTION ON UPDATE NO ACTION
);