ALTER TABLE `PACIENTE` 
ADD COLUMN `ID_PLANO` BIGINT(20) NULL AFTER `ID_PESSOA`,
ADD INDEX `FK_PACIENTE_PLANO_idx` (`ID_PLANO` ASC) VISIBLE;
;
ALTER TABLE `PACIENTE` 
ADD CONSTRAINT `FK_PACIENTE_PLANO`
  FOREIGN KEY (`ID_PLANO`)
  REFERENCES `PLANO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
