ALTER TABLE `ENDERECO_PF` 
DROP FOREIGN KEY `FK_ENDERECO_PESSOA`;
ALTER TABLE `ENDERECO_PF` 
CHANGE COLUMN `ID_PESSOA` `ID_PESSOA` BIGINT(20) NULL ,
CHANGE COLUMN `LOGRADOURO` `LOGRADOURO` VARCHAR(200) NULL ,
CHANGE COLUMN `NUMERO` `NUMERO` VARCHAR(10) NULL ,
CHANGE COLUMN `ESTADO` `ESTADO` VARCHAR(2) NULL ,
CHANGE COLUMN `BAIRRO` `BAIRRO` VARCHAR(100) NULL ,
CHANGE COLUMN `CIDADE` `CIDADE` VARCHAR(100) NULL ;
ALTER TABLE `ENDERECO_PF` 
ADD CONSTRAINT `FK_ENDERECO_PESSOA`
  FOREIGN KEY (`ID_PESSOA`)
  REFERENCES `PESSOA_FISICA` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
