ALTER TABLE `devdb`.`USUARIO` 
ADD COLUMN `DATA_NASCIMENTO` DATE NULL AFTER `ATIVO`,
ADD COLUMN `NOME_MAE` VARCHAR(200) NULL AFTER `DATA_NASCIMENTO`;

UPDATE USUARIO SET DATA_NASCIMENTO = STR_TO_DATE('01/09/2019', '%m/%d/%Y'), NOME_MAE = 'FRIENDS TEAM' WHERE ID = 1;

ALTER TABLE `devdb`.`USUARIO` 
CHANGE COLUMN `DATA_NASCIMENTO` `DATA_NASCIMENTO` DATE NOT NULL ,
CHANGE COLUMN `NOME_MAE` `NOME_MAE` VARCHAR(200) NOT NULL ;
