CREATE TABLE `AGENDAMENTO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` BIGINT(20) NOT NULL,
  `ID_RESPONSAVEL` BIGINT(20) NOT NULL,
  `DATA_HORA` DATETIME NOT NULL,
  `ANOTACOES` VARCHAR(200) NULL,
  `SITUACAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_AGENDA_PACIENTE_idx` (`ID_PACIENTE` ASC),
  INDEX `FK_AGENDA_RESPONS_idx` (`ID_RESPONSAVEL` ASC),
  CONSTRAINT `FK_AGENDA_PACIENTE`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `PACIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AGENDA_RESPONS`
    FOREIGN KEY (`ID_RESPONSAVEL`)
    REFERENCES `RESPONSAVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
