ALTER TABLE `PESSOA_FISICA` 
ADD COLUMN `ID_USUARIO` BIGINT(20) NULL AFTER `SEXO`;

ALTER TABLE `PESSOA_FISICA` 
ADD INDEX `FK_PESSOA_USUARIO_idx` (`ID_USUARIO` ASC);
ALTER TABLE `PESSOA_FISICA` 
ADD CONSTRAINT `FK_PESSOA_USUARIO`
  FOREIGN KEY (`ID_USUARIO`)
  REFERENCES `USUARIO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `RESPONSAVEL` 
DROP COLUMN `NOME`,
CHANGE COLUMN `USUARIO` `ID_PESSOA` BIGINT(20) NOT NULL ;

ALTER TABLE `RESPONSAVEL` 
ADD INDEX `FK_RESPONSAVEL_PESSOA_idx` (`ID_PESSOA` ASC);
ALTER TABLE `RESPONSAVEL` 
ADD CONSTRAINT `FK_RESPONSAVEL_PESSOA`
  FOREIGN KEY (`ID_PESSOA`)
  REFERENCES `PESSOA_FISICA` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
