CREATE TABLE `ALERGIA` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`, `DESCRICAO`),
  UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC));

DROP TABLE `PACIENTE_ALERGIA`;
  
CREATE TABLE `PACIENTE_ALERGIA` (
  `ID_PACIENTE` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_PACIENTE`, `DESCRICAO`),
  UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC),
  CONSTRAINT `FK_ALERGIA_PACIENTE`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `PACIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
