CREATE TABLE `PLANO` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_OPERADORA` BIGINT(20) NOT NULL,
  `COD_PLAN` BIGINT(20) NOT NULL,
  `NOME_COMERCIAL` VARCHAR(300) NOT NULL,
  `SEGMENTACAO` VARCHAR(100) NOT NULL,
  `TIPO_CONTRATO` VARCHAR(80) NOT NULL,
  `ABRANGENCIA` VARCHAR(50) NOT NULL,
  `TIPO_PLANO` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COD_PLAN_UK` (`COD_PLAN` ASC),
  INDEX `FK_PLANO_OPERADORA_idx` (`ID_OPERADORA` ASC),
  CONSTRAINT `FK_PLANO_OPERADORA`
    FOREIGN KEY (`ID_OPERADORA`)
    REFERENCES `OPERADORA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
