CREATE TABLE `AGENDA_CONFIRMACAO` (
  `ID` VARCHAR(100) NOT NULL,
  `SITUACAO` VARCHAR(45) NOT NULL,
  `DATA_HORA_RESP` DATETIME NOT NULL,
  `IP_RESPOSTA` VARCHAR(45) NOT NULL,
  `ID_PACIENTE` BIGINT(20) NOT NULL,
  `ID_RESPONSAVEL` BIGINT(20) NOT NULL,
  `DATA_CRIACAO` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_AG_CONF_PAC_idx` (`ID_PACIENTE` ASC),
  INDEX `FK_AG_CONF_RESP_idx` (`ID_RESPONSAVEL` ASC),
  CONSTRAINT `FK_AG_CONF_PAC`
    FOREIGN KEY (`ID_PACIENTE`)
    REFERENCES `PACIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AG_CONF_RESP`
    FOREIGN KEY (`ID_RESPONSAVEL`)
    REFERENCES `RESPONSAVEL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
