CREATE TABLE `UNIDADE_MEDIDA` (
 `ID` BIGINT(20) NOT NULL,
 `DESCRICAO` VARCHAR(100) NOT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC)); 

INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('001', 'AMP Ampola');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('002', 'BUI Bilhões de Unidades Internacionais');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('003', 'BG Bisnaga');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('004', 'BOLS Bolsa');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('005', 'CX Caixa');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('006', 'CAP Cápsula');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('007', 'CARP Carpule');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('008', 'COM Comprimido');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('009', 'DOSE Dose');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('010', 'DRG Drágea');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('011', 'ENV Envelope');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('012', 'FLAC Flaconete');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('013', 'FR Frasco');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('014', 'FA Frasco Ampola');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('015', 'GAL Galão');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('016', 'GLOB Glóbulo');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('017', 'GTS Gotas');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('018', 'G Grama');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('019', 'L Litro');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('020', 'MCG Microgramas');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('021', 'MUI Milhões de Unidades Internacionais');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('022', 'MG Miligrama');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('023', 'ML Milílitro');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('024', 'OVL Óvulo');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('025', 'PAS Pastilha');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('026', 'LT Lata');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('027', 'PER Pérola');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('028', 'PIL Pílula');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('029', 'PT Pote');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('030', 'KG Quilograma');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('031', 'SER Seringa');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('032', 'SUP Supositório');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('033', 'TABLE Tablete');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('034', 'TUB Tubete');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('035', 'TB Tubo');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('036', 'UN Unidade');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('037', 'UI Unidade Internacional');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('038', 'CM Centímetro');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('039', 'CONJ Conjunto');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('040', 'KIT Kit');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('041', 'MÇ Maço');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('042', 'M Metro');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('043', 'PC Pacote');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('044', 'PÇ Peça');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('045', 'RL Rolo');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('046', 'GY Gray');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('047', 'CGY Centgray');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('048', 'PAR Par');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('049', 'ADES Adesivo Transdérmico');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('050', 'COM EFEV Comprimido Efervecente');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('051', 'COM MST Comprimido Mastigável');
INSERT INTO `UNIDADE_MEDIDA` (`ID`, `DESCRICAO`) VALUES ('052', 'SACHE Sache');

