CREATE TABLE `DOCUMENTO_PESSOA` (
	`ID_PESSOA` BIGINT(20) NOT NULL,
	`TIPO_DOCUMENTO` VARCHAR(50) NOT NULL,
	`VALOR` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`ID_PESSOA`, `TIPO_DOCUMENTO`, `VALOR`),
	CONSTRAINT `FK_DOC_PESSOA` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`) ON UPDATE RESTRICT ON DELETE CASCADE
);

UPDATE INSTITUTO 
	SET 
		`CNPJ` = '68825375000124' AND
		`NOME` = 'NIV LABS' AND
		`NOME_CORPORATIVO` = 'NIV LABS' AND
		`LOGO` = NULL AND
		`LOGRADOURO` = 'NÃO INFORMADO' AND
		`CEP` = '11123123' AND
		`ESTADO` = 'PE' AND
		`BAIRRO` = 'BOA VIAGEM' AND
		`CIDADE` = 'RECIFE' AND
		`TELEFONE` = '8112341234' AND
		`DEPENDENCIA` = 'NÃO INFORMADO' AND
		`GESTOR` = 'NÃO INFORMADO' AND
		`TELEFONE_GESTOR` ='81112341234' AND
		`EMAIL_GESTOR` = 'atendimento@nivlabs.com.br'
WHERE `NOME` = 'Georgia Ferreira'

