CREATE TABLE `PESSOA_FISICA` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(200) NOT NULL,
  `NOMEFANTASIA` VARCHAR(200) NOT NULL,
  `RG` VARCHAR(7) NULL,
  `CPF` VARCHAR(16) NOT NULL,
  `DATA_NASCIMENTO` DATE NOT NULL,
  `NOME_COMP_PAI` VARCHAR(200) NULL,
  `NOME_COMP_MAE` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`));
