CREATE TABLE `ESPECIALIDADE`
(
   `ID` BIGINT (20) NOT NULL AUTO_INCREMENT,
   `NOME` VARCHAR (45) NOT NULL,
   `DESCRICAO` VARCHAR (200) NULL,
   PRIMARY KEY (`ID`)
);
CREATE TABLE `ESPECIALIDADE_RESPONSAVEL`
(
   `ID_ESPECIALIDADE` BIGINT (20) NOT NULL,
   `ID_RESPONSAVEL` BIGINT (20) NOT NULL,
   PRIMARY KEY
   (
      `ID_ESPECIALIDADE`,
      `ID_RESPONSAVEL`
   )
);
ALTER TABLE `ESPECIALIDADE_RESPONSAVEL` ADD INDEX `FK_RESPONSAVEL_ESPECIALIDADE_idx`
(
   `ID_RESPONSAVEL` ASC
);
ALTER TABLE `ESPECIALIDADE_RESPONSAVEL` ADD CONSTRAINT `FK_ESPECIALIDADE_RESPONSAVEL` FOREIGN KEY (`ID_ESPECIALIDADE`) REFERENCES `ESPECIALIDADE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_RESPONSAVEL_ESPECIALIDADE` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;