CREATE TABLE `PRESCRICAO` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`ID_VISITA` BIGINT(20) NOT NULL,
	`ID_RESPONSAVEL` BIGINT(20) NOT NULL,
	`DATA_INICIO` DATETIME NOT NULL,
	`DATA_FIM` DATETIME NOT NULL,
	PRIMARY KEY (`ID`),
	CONSTRAINT `FK_PRESC_VISITA` FOREIGN KEY (`ID_VISITA`) REFERENCES `VISITA` (`ID`),	
	CONSTRAINT `FK_PRESC_RESP` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`)
)