
 CREATE TABLE `TABELA_CBO` (
  `ID` BIGINT(20) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DESCRICAO_UNIQUE` (`DESCRICAO` ASC));
  
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('201115', 'Geneticista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('203015', 'Pesquisador em biologia de microorganismos e parasitas');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('213150', 'Físico médico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('221105', 'Biólogo');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223204', 'Cirurgião dentista - auditor');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223208', 'Cirurgião dentista - clínico geral');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223212', 'Cirurgião dentista - endodontista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223216', 'Cirurgião dentista - epidemiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223220', 'Cirurgião dentista - estomatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223224', 'Cirurgião dentista - implantodontista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223228', 'Cirurgião dentista - odontogeriatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223232', 'Cirurgião dentista - odontologista legal');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223236', 'Cirurgião dentista - odontopediatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223240', 'Cirurgião dentista - ortopedista e ortodontista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223244', 'Cirurgião dentista - patologista bucal');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223248', 'Cirurgião dentista - periodontista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223252', 'Cirurgião dentista - protesiólogo bucomaxilofacial');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223256', 'Cirurgião dentista - protesista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223260', 'Cirurgião dentista - radiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223264', 'Cirurgião dentista - reabilitador oral');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223268', 'Cirurgião dentista - traumatologista bucomaxilofacial');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223272', 'Cirurgião dentista de saúde coletiva');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223276', 'Cirurgião dentista - odontologia do trabalho');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223280', 'Cirurgião dentista - dentística');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223284', 'Cirurgião dentista - disfunção temporomandibular e dor orofacial');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223288', 'Cirurgião dentista - odontologia para pacientes com necessidades especiais');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223293', 'Cirurgião-dentista da estratégia de saúde da família');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223505', 'Enfermeiro');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223605', 'Fisioterapeuta geral');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223710', 'Nutricionista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223810', 'Fonoaudiólogo');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223905', 'Terapeuta ocupacional');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('223910', 'Ortoptista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225103', 'Médico infectologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225105', 'Médico acupunturista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225106', 'Médico legista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225109', 'Médico Nefrologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225110', 'Médico alergista e imunologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225112', 'Médico neurologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225115', 'Médico angiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225118', 'Médico nutrologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225120', 'Médico cardiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225121', 'Médico oncologista clínico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225122', 'Médico cancerologista pediátrico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225124', 'Médico pediatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225125', 'Médico clínico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225127', 'Médico pneumologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225130', 'Médico de família e comunidade');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225133', 'Médico psiquiatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225135', 'Médico dermatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225136', 'Médico reumatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225139', 'Médico sanitarista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225140', 'Médico do trabalho');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225142', 'Médico da estratégia de saúde da família');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225145', 'Médico em medicina de tráfego');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225148', 'Médico anatomopatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225150', 'Médico em medicina intensiva');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225151', 'Médico anestesiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225155', 'Médico endocrinologista e metabologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225160', 'Médico fisiatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225165', 'Médico gastroenterologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225170', 'Médico generalista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225175', 'Médico geneticista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225180', 'Médico geriatra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225185', 'Médico Hematologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225195', 'Médico Homeopata');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225203', 'Médico em cirurgia vascular');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225210', 'Médico cirurgião cardiovascular');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225215', 'Médico cirurgião de cabeça e pescoço');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225220', 'Médico cirurgião do aparelho digestivo');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225225', 'Médico cirurgião geral');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225230', 'Médico cirurgião pediátrico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225235', 'Médico cirurgião plástico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225240', 'Médico cirurgião torácico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225250', 'Médico ginecologista e obstetra');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225255', 'Médico Mastologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225260', 'Médico neurocirurgião');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225265', 'Médico oftalmologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225270', 'Médico ortopedista e traumatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225275', 'Médico otorrinolaringologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225280', 'Médico proctologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225285', 'Médico urologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225290', 'Médico cancerologista cirúrgico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225295', 'Médico cirurgião da mão');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225305', 'Médico citopatologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225310', 'Médico em endoscopia');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225315', 'Médico em medicina nuclear');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225320', 'Médico em radiologia e diagnóstico por imagem');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225325', 'Médico patologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225330', 'Médico radioterapeuta');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225335', 'Médico patologista clínico / medicina laboratorial');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225340', 'Médico hemoterapeuta');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225345', 'Médico hiperbarista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('225350', 'Médico neurofisiologista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('239425', 'Psicopedagogo');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('251510', 'Psicólogo clínico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('251545', 'Neuropsicólogo');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('251550', 'Psicanalista');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('251605', 'Assistente social');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('322205', 'Técnico de enfermagem');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('322220', 'Técnico de enfermagem psiquiátrica');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('322225', 'Instrumentador cirúrgico');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('322230', 'Auxiliar de enfermagem');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('516210', 'Cuidador de idosos');
INSERT INTO TABELA_CBO (`ID`, `DESCRICAO`) VALUES ('999999', 'CBO desconhecido ou não informado pelo solicitante');