ALTER TABLE `ENDERECO_PF` 
DROP FOREIGN KEY `FK_ENDERECO_PESSOA`;
ALTER TABLE `ENDERECO_PF` 
CHANGE COLUMN `ID_PESSOA` `ID_PESSOA` BIGINT(20) NOT NULL ,
ADD UNIQUE INDEX `ID_PESSOA_UNIQUE` (`ID_PESSOA` ASC);
ALTER TABLE `ENDERECO_PF` 
ADD CONSTRAINT `FK_ENDERECO_PESSOA`
  FOREIGN KEY (`ID_PESSOA`)
  REFERENCES `PESSOA_FISICA` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
