ALTER TABLE `TIPO_EVENTO` 
ADD COLUMN `ID_TIPO_EVENTO` BIGINT(20) NULL AFTER `ID`	,
ADD INDEX `FK_RECURSIVA_idx` (`ID_TIPO_EVENTO` ASC);
ALTER TABLE `TIPO_EVENTO` 
ADD CONSTRAINT `FK_RECURSIVA`
  FOREIGN KEY (`ID_TIPO_EVENTO`)
  REFERENCES `TIPO_EVENTO` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

INSERT INTO `TIPO_EVENTO` (`ID`, `NOME`, `DESCRICAO`) VALUES ('1', 'ENTRADA', 'Entrada da visita');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('2', '1', 'ENTRADA_EMERGENCIA', 'Entrada da visita na emergência');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('3', '1', 'ENTRADA_CONSULTA', 'Entrada à partir de uma consulta');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('4', '1', 'ANAMNESE', 'Geração de Anamnese');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('5', '1', 'TRIAGEM', 'Triagem');

INSERT INTO `TIPO_EVENTO` (`ID`, `NOME`, `DESCRICAO`) VALUES ('6', 'PRESCRICAO', 'Prescrição');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('8', '6', 'CRIACAO_PRESCRICAO', 'Criação de prescrição na visita');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('9', '6', 'REMOCAO_PRESCRICAO', 'Remoção de prescrição na visita');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('10', '6', 'ALTERACAO_PRESCRICAO', 'Alteração na prescrição da visita');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('11', '6', 'APLICACAO_MEDICAMENTO', 'Aplicação de medicamento no paciente');

INSERT INTO `TIPO_EVENTO` (`ID`, `NOME`, `DESCRICAO`) VALUES ('12', 'MEDICAMENTO', 'Medicamento');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('13', '12', 'ADICAO_MEDICAMENTO', 'Adição de medicamento na prescrição');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('114', '12', 'REMOCAO_MEDICAMENTO', 'Remoção de medicamento da prescrição');

INSERT INTO `TIPO_EVENTO` (`ID`, `NOME`, `DESCRICAO`) VALUES ('15', 'EVOLUCAO', 'Relização de evolução clínica');

INSERT INTO `TIPO_EVENTO` (`ID`, `NOME`, `DESCRICAO`) VALUES ('16', 'ALTA', 'Relização de alta da visita');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('17', '16', 'ALTA_RESIDENCIA', 'Melhorado, curado, evasão, administrativa');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('18', '16', 'ALTA_OBITO', 'Alta por óbito');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('19', '16', 'ALTA_HOSPITALAR', 'Transferência externa (Paciente de outro hospital)');
INSERT INTO `TIPO_EVENTO` (`ID`, `ID_TIPO_EVENTO`, `NOME`, `DESCRICAO`) VALUES ('20', '16', 'ALTA_TRANSFERENCIA', 'Alta por transferência (Paciente para outro hospital)');

