INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(1, 'ROLE_ADMIN', 'Acesso de administrador do sistema');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(2, 'ROLE_ATENDIMENTO_LEITURA', 'Permissão de leitura em prontuário');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(3, 'ROLE_ATENDIMENTO_ESCRITA', 'Permissão de escrita em prontuário');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(4, 'ROLE_PACIENTE_LEITURA', 'Permissão de leitura em paciente');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(5, 'ROLE_PACIENTE_ESCRITA', 'Permissão de escrita em paciente');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(6, 'ROLE_PROFISSIONAL_LEITURA', 'Permissão de leitura em profissional');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(7, 'ROLE_PROFISSIONAL_ESCRITA', 'Permissão de escrita em profissional');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(8, 'ROLE_EVENTO_LEITURA', 'Permissão de leitura em evento');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(9, 'ROLE_EVENTO_ESCRITA', 'Permissão de escrita em evento');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(10, 'ROLE_SETOR_LEITURA', 'Permissão de leitura em setor');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(11, 'ROLE_SETOR_ESCRITA', 'Permissão de escrita em setor');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(12, 'ROLE_DOCUMENTO_LEITURA', 'Permissão de leitura em documentos digitais');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(13, 'ROLE_DOCUMENTO_ESCRITA', 'Permissão de escrita em documentos digitais');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(14, 'ROLE_INSTITUTO_LEITURA', 'Permissão de leitura em informações intitucionais');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(15, 'ROLE_INSTINTUTO_ESCRITA', 'Permissão de escrita em informações intitucionais');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(16, 'ROLE_PARAMETRO_LEITURA', 'Permissão de leitura em parâmetros da aplicação');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(17, 'ROLE_PARAMETRO_ESCRITA', 'Permissão de escrita em parâmetros da aplicação');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(18, 'ROLE_OPERADORA_LEITURA', 'Permissão de leitura em operadoras de planos');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(19, 'ROLE_OPERADORA_ESCRITA', 'Permissão de escrita em operadoras de planos');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(20, 'ROLE_ATENDIMENTO_ALTA', 'Permissão de criar evento de alta clínica (Prontuário)');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(21, 'ROLE_AGENDA_LEITURA', 'Permissão de leitura em agenda');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(22, 'ROLE_AGENDA_ESCRITA', 'Permissão de escrita em agenda');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(23, 'ROLE_ESPECIALIDADE_LEITURA', 'Permissão de leitura em especialidade');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(24, 'ROLE_ESPECIALIDADE_ESCRITA', 'Permissão de escrita em especialidade');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(25, 'ROLE_RELATORIO_LEITURA', 'Permissão de leitura em relatórios');
INSERT INTO PERMISSAO
(ID, NOME, DESCRICAO)
VALUES(26, 'ROLE_RELATORIO_ESCRITA', 'Permissão de escrita em relatórios');

INSERT INTO `PESSOA_FISICA` (`ID`, `NOME_COMPLETO`, `NOME_SOCIAL`, `RG`, `CPF`, `DATA_NASCIMENTO`, `NOME_COMP_PAI`, `NOME_COMP_MAE`, `SEXO`, `TELEFONE_PRINCIPAL`, `TELEFONE_SECUNDARIO`, `FOTO`, `IDENTIDADE_GENERO`, `EMAIL`) VALUES (1, 'Administrador', 'Principal', '0000000', '11122233396', '2020-12-15', 'Não Informado', 'Não Informado', 'M', NULL, NULL, NULL, 'HETERO', 'atendimento@nivlabs.com.br');

INSERT INTO `USUARIO` (`ID`, `USUARIO`, `SENHA`, `ATIVO`, `ID_PESSOA`, `DATA_CRIACAO`) VALUES
	(1, 'ADMIN', '$2a$10$XIMO9M5wVNb236vYW2N2hO3mgbWcjBE4sL5MyBLEqsnUKrY2sYKXS', 1, 1, sysdate());

INSERT INTO USUARIO_PERMISSAO (ID_USUARIO, ID_PERMISSAO) VALUES(1, 1);

INSERT INTO `INSTITUTO` (`CGC`, `CNES`, `NOME`, `LOGO`, `NOME_CORPORATIVO`, `NATUREZA_LEGAL`, `LOGRADOURO`, `NUMERO`, `COMPLEMENTO`, `CEP`, `ESTADO`, `BAIRRO`, `CIDADE`, `TELEFONE`, `DEPENDENCIA`, `TIPO_DE_INSTITUICAO`, `GESTOR`, `TELEFONE_GESTOR`, `EMAIL_GESTOR`, `DATA_DE_REGISTRO`, `USUARIO_DE_REGISTRO`, `CHAVE_ACESSO`, `DATA_INICIO`, `DATA_FIM`) VALUES
	('38155049000196', '0000000', 'Clínica CliNiv',null, 'Clínica CliNiv', 'MEI', 'Avenida Visconde de Suassuna', '200', 'Sala 4', '50050540', 'PE', 'SANTO AMARO', 'RECIFE', '81999509300', 'VINÍCIOS DE ARAÚJO RODRIGUES', 'PRIVADA', 'VINÍCIOS DE ARAÚJO RODRIGUES', '81999509300', 'atendimento@nivlabs.com.br', DATE_FORMAT(sysdate(),'%Y-%m-%d'), 'admin', '4ijh32i4-43hnui4h-4n3ui4hn3-4nm3i43', '2023-12-15 17:30:17', '2024-12-15 17:30:17');

INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(1, 'ENABLE_SEARCH_BY_ZIP_CODE', 'Liga | Desliga integração com busca de CEP', 'INTEGRAÇÃO CEP', 'BOOL', 'true', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(2, 'ZIP_CODE_SEARCH_PROVIDER', 'API de integração de busca de CEP', 'INTEGRAÇÃO CEP', 'GROUP', 'VIA_CEP', 'VIA_CEP');
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(3, 'AGENDA_OPENING_TIME', 'Hora de abertura da agenda', 'AGENDA', 'STRING', '00:00', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(4, 'AGENDA_CLOSING_TIME', 'Hora de encerramento da agenda', 'AGENDA', 'STRING', '23:59', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(5, 'BREAK_TIME_BETWEEN_SCHEDULE_TIMES', 'Intervalos entre horários da agenda', 'AGENDA', 'NUMBER', '60', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(6, 'BLOCK_OUT_OF_SCHEDULE_APPOINTMENT', 'Bloquear agendamento fora do horário', 'AGENDA', 'BOOL', 'true', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(7, 'BLOCKS_READING_THE_MEDICAL_RECORD_WITHOUT_ACTIVE_SERVICE', 'Bloquear leitura de prontuário sem atendimento ativo', 'ATENDIMENTO', 'BOOL', 'false', NULL);
INSERT INTO APP_PARAM
(ID, ALIAS, NOME, GRUPO, TIPO, VALOR, VALORES_DE_GRUPO)
VALUES(8, 'ENABLE_SERVICE_SHARING', 'Compartilhar atendimentos entre profissionais', 'ATENDIMENTO', 'BOOL', 'true', NULL);

	
INSERT INTO `SETOR` (`ID`, `DESCRICAO`, `DATA_CRIACAO`) VALUES
	(1, 'ATENDIMENTO', sysdate());
	
INSERT INTO `SALA_LEITO` (`ID`, `NOME`, `TIPO`, `SECTOR_ID`) VALUES
	(1, 'REMOTO', 'ROOM', 1);
