CREATE TABLE `PESSOA_FISICA` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME_COMPLETO` varchar(200) NOT NULL,
  `NOME_SOCIAL` varchar(200)  DEFAULT NULL,
  `RG` varchar(7) DEFAULT NULL,
  `CPF` varchar(16) DEFAULT NULL,
  `DATA_NASCIMENTO` date DEFAULT NULL,
  `NOME_COMP_PAI` varchar(200) DEFAULT NULL,
  `NOME_COMP_MAE` varchar(200) DEFAULT NULL,
  `SEXO` varchar(1) DEFAULT NULL,
  `TELEFONE_PRINCIPAL` varchar(30) DEFAULT NULL,
  `TELEFONE_SECUNDARIO` varchar(30) DEFAULT NULL,
  `FOTO` longblob,
  `IDENTIDADE_GENERO` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  `GRUPO_ETNICO` varchar(45) DEFAULT NULL,
  `TIPO_SANGUINEO` varchar(45) DEFAULT NULL,
  `NACIONALIDADE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CPF_UNIQUE` (`CPF`)
);

CREATE TABLE `ENDERECO_PF` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` bigint NOT NULL,
  `LOGRADOURO` varchar(200) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `COMPLEMENTO` varchar(50) DEFAULT NULL,
  `CODIGO_POSTAL` varchar(8) DEFAULT NULL,
  `ESTADO` varchar(2) DEFAULT NULL,
  `BAIRRO` varchar(100) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_PESSOA_UNIQUE` (`ID_PESSOA`),
  KEY `FK_ENDERECO_PESSOA_idx` (`ID_PESSOA`),
  CONSTRAINT `FK_ENDERECO_PESSOA` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`)
);

CREATE TABLE `DOCUMENTO_PESSOA` (
  `ID_PESSOA` bigint NOT NULL,
  `TIPO_DOCUMENTO` varchar(50) NOT NULL,
  `VALOR` varchar(100) NOT NULL,
  `EXPEDIDOR` varchar(100) DEFAULT NULL,
  `DATA_EXPEDICAO` date DEFAULT NULL,
  `VALIDADE` date DEFAULT NULL,
  `UF_EXPEDICAO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID_PESSOA`,`TIPO_DOCUMENTO`,`VALOR`),
  CONSTRAINT `FK_DOC_PESSOA` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`) ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE `OPERADORA` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `RAZAO_SOCIAL` varchar(300) NOT NULL,
  `COD_ANS` varchar(30) NOT NULL,
  `CNPJ` varchar(16) NOT NULL,
  `NOME_FANTASIA` varchar(300) NOT NULL,
  `MODALIDADE` varchar(45) NOT NULL COMMENT 'Operadoras possíveis:\\n- Operadoras de planos de saúde\\n- Cooperativa médica/odontológica\\n- Autogestão\\n- Filantropia\\n- Administradora\\n- Seguradoras de saúde',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COD_ANS_UK` (`COD_ANS`),
  UNIQUE KEY `CNPJ_UK` (`CNPJ`)
);

CREATE TABLE `PLANO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_OPERADORA` bigint NOT NULL,
  `COD_PLAN` bigint NOT NULL,
  `NOME_COMERCIAL` varchar(300) NOT NULL,
  `SEGMENTACAO` varchar(100) NOT NULL,
  `TIPO_CONTRATO` varchar(80) NOT NULL,
  `ABRANGENCIA` varchar(50) NOT NULL,
  `TIPO_PLANO` varchar(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `COD_PLAN_UK` (`COD_PLAN`),
  KEY `FK_PLANO_OPERADORA_idx` (`ID_OPERADORA`),
  CONSTRAINT `FK_PLANO_OPERADORA` FOREIGN KEY (`ID_OPERADORA`) REFERENCES `OPERADORA` (`ID`)
);

CREATE TABLE `USUARIO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(80) NOT NULL,
  `SENHA` varchar(500) DEFAULT NULL,
  `ATIVO` int NOT NULL DEFAULT '1',
  `ID_PESSOA` bigint NOT NULL,
  `PRIMEIRO_LOGIN` int NOT NULL DEFAULT '1',
  `DATA_CRIACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USUARIO_UNIQUE` (`USUARIO`),
  KEY `FK_USUARIO_PESSOA` (`ID_PESSOA`),
  CONSTRAINT `FK_USUARIO_PESSOA` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`)
);

CREATE TABLE `PERMISSAO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `DESCRICAO` varchar(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOME_UNIQUE` (`NOME`)
);

CREATE TABLE `USUARIO_PERMISSAO` (
  `ID_USUARIO` bigint NOT NULL,
  `ID_PERMISSAO` bigint NOT NULL,
  PRIMARY KEY (`ID_USUARIO`,`ID_PERMISSAO`),
  KEY `fk_PERMISSAO_USUARIO` (`ID_PERMISSAO`),
  CONSTRAINT `fk_PERMISSAO_USUARIO` FOREIGN KEY (`ID_PERMISSAO`) REFERENCES `PERMISSAO` (`ID`),
  CONSTRAINT `fk_USUARIO_PERMISSAO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID`)
);

CREATE TABLE `TEMPLATE_DOC` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` bigint NOT NULL,
  `DESCRICAO` varchar(200) NOT NULL,
  `TEXTO_TEMPLATE` blob NOT NULL,
  PRIMARY KEY (`ID`,`ID_USUARIO`),
  KEY `FK_TEMPLATE_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `FK_TEMPLATE_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID`)
);

CREATE TABLE `RESPONSAVEL` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` bigint NOT NULL,
  `REGISTRO_PROFISSIONAL` varchar(100) DEFAULT NULL,
  `SIGLA_ORGAO` varchar(45) DEFAULT NULL,
  `DATA_CRIACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `FK_RESPONSAVEL_PESSOA_idx` (`ID_PESSOA`),
  CONSTRAINT `FK_RESPONSAVEL_PESSOA` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`)
);

CREATE TABLE `ESPECIALIDADE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) NOT NULL,
  `DESCRICAO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ESPECIALIDADE_RESPONSAVEL` (
  `ID_ESPECIALIDADE` bigint NOT NULL,
  `ID_RESPONSAVEL` bigint NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDADE`,`ID_RESPONSAVEL`),
  KEY `FK_RESPONSAVEL_ESPECIALIDADE_idx` (`ID_RESPONSAVEL`),
  CONSTRAINT `FK_ESPECIALIDADE_RESPONSAVEL` FOREIGN KEY (`ID_ESPECIALIDADE`) REFERENCES `ESPECIALIDADE` (`ID`),
  CONSTRAINT `FK_RESPONSAVEL_ESPECIALIDADE` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`)
);

CREATE TABLE `PACIENTE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_PESSOA` bigint NOT NULL,
  `ID_PLANO` bigint DEFAULT NULL,
  `NUMERO_PLANO` varchar(50) DEFAULT NULL,
  `CODIGO_SUS` varchar(15) DEFAULT NULL,
  `TIPO_PACIENTE` varchar(15) NOT NULL,
  `ANOTACOES` varchar(10000) DEFAULT NULL,
  `DATA_CRIACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_PACIENTE` (`ID`,`ID_PESSOA`),
  UNIQUE KEY `ID_PESSOA_UNIQUE` (`ID_PESSOA`),
  UNIQUE KEY `CODIGO_SUS_UNIQUE` (`CODIGO_SUS`),
  KEY `FK_PACIENTE_PESSOA_F_idx` (`ID_PESSOA`),
  KEY `FK_PACIENTE_PLANO_idx` (`ID_PLANO`),
  CONSTRAINT `FK_PACIENTE_PESSOA_F` FOREIGN KEY (`ID_PESSOA`) REFERENCES `PESSOA_FISICA` (`ID`),
  CONSTRAINT `FK_PACIENTE_PLANO` FOREIGN KEY (`ID_PLANO`) REFERENCES `PLANO` (`ID`)
);

CREATE TABLE `PACIENTE_ALERGIA` (
  `ID_PACIENTE` bigint NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID_PACIENTE`,`DESCRICAO`),
  CONSTRAINT `FK_ALERGIA_PACIENTE` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `PACIENTE` (`ID`)
);

CREATE TABLE `SETOR` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  `DATA_CRIACAO` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SETOR_ID_IDX` (`ID`)
);

CREATE TABLE `SALA_LEITO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME` varchar(120) NOT NULL,
  `TIPO` varchar(20) NOT NULL DEFAULT 'ROOM',
  `SECTOR_ID` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SALA_LEITO_FK` (`SECTOR_ID`),
  CONSTRAINT `SALA_LEITO_FK` FOREIGN KEY (`SECTOR_ID`) REFERENCES `SETOR` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `VISITA` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `PROFISSIONAL_ATUAL` bigint DEFAULT NULL,
  `ACOMODACAO_ATUAL` bigint NOT NULL,
  `TIPO_ENTRADA` varchar(45) NOT NULL,
  `ID_PACIENTE` bigint NOT NULL,
  `DH_ENTRADA` datetime NOT NULL,
  `DH_SAIDA` datetime DEFAULT NULL,
  `MOTIVO_ENTRADA` varchar(5000) NOT NULL,
  `NIVEL_RISCO` varchar(10) NOT NULL DEFAULT 'LOW',
  PRIMARY KEY (`ID`),
  KEY `fk_VISITA_PACIENT_idx` (`ID_PACIENTE`),
  KEY `FK_VISITA_ACOMOD_idx` (`ACOMODACAO_ATUAL`),
  CONSTRAINT `FK_VISITA_ACOMOD` FOREIGN KEY (`ACOMODACAO_ATUAL`) REFERENCES `SALA_LEITO` (`ID`),
  CONSTRAINT `fk_VISITA_PACIENT` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `PACIENTE` (`ID`)
);

CREATE TABLE `PROCEDIMENTO` (
  `ID` bigint NOT NULL,
  `DESCRICAO` varchar(500) NOT NULL,
  `ATIVO` int NOT NULL,
  `VALOR_BASE` double DEFAULT NULL,
  `PERIOCIDADE` varchar(45) DEFAULT NULL,
  `REQ_AUTORIZACAO_ESPECIAL` int DEFAULT '0',
  `REQ_AUDIT_PREV` int DEFAULT '0',
  `REQ_ESPECIALIDADE` int DEFAULT '0',
  `IDADE_MAX` varchar(45) DEFAULT NULL,
  `IDADE_MIN` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
);

CREATE TABLE `TIPO_EVENTO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_TIPO_EVENTO` bigint DEFAULT NULL,
  `NOME` varchar(45) NOT NULL,
  `DESCRICAO` varchar(200) DEFAULT NULL,
  `PROCEDIMENTO_EQ_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CBHPM_EQUIVALENTE_UNIQUE` (`PROCEDIMENTO_EQ_ID`),
  KEY `FK_RECURSIVA_idx` (`ID_TIPO_EVENTO`),
  CONSTRAINT `FK_RECURSIVA` FOREIGN KEY (`ID_TIPO_EVENTO`) REFERENCES `TIPO_EVENTO` (`ID`),
  CONSTRAINT `fk_TIPO_EVENTO_PROC` FOREIGN KEY (`PROCEDIMENTO_EQ_ID`) REFERENCES `PROCEDIMENTO` (`ID`)
);

CREATE TABLE `VISITA_EVENTO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_VISITA` bigint NOT NULL,
  `ID_RESPONSAVEL` bigint DEFAULT NULL,
  `ID_SALA_LEITO` bigint NOT NULL,
  `ID_PROCEDIMENTO` bigint DEFAULT NULL,
  `TITULO` varchar(500) NOT NULL,
  `OBSERVACOES` blob,
  `DH_EVENTO` datetime NOT NULL,
  `TIPO_EVENTO` varchar(80) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_VISITA_VISITA_idx` (`ID_VISITA`),
  KEY `fk_VISITA_RESP_idx` (`ID_RESPONSAVEL`),
  KEY `fk_VISITA_PROCEDIMENTO_idx` (`ID_PROCEDIMENTO`),
  KEY `fk_VISITA_SALA_LEITO_idx` (`ID_SALA_LEITO`),
  CONSTRAINT `fk_VISITA_EVENTO_VISITA` FOREIGN KEY (`ID_VISITA`) REFERENCES `VISITA` (`ID`),
  CONSTRAINT `fk_VISITA_PROCEDIMENTO` FOREIGN KEY (`ID_PROCEDIMENTO`) REFERENCES `PROCEDIMENTO` (`ID`),
  CONSTRAINT `fk_VISITA_RESP` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`),
  CONSTRAINT `fk_VISITA_SALA_LEITO` FOREIGN KEY (`ID_SALA_LEITO`) REFERENCES `SALA_LEITO` (`ID`)
);

CREATE TABLE `DOCUMENTO_DIGITAL` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_VISITA_EVENTO` bigint NOT NULL,
  `TIPO` varchar(45)  NOT NULL,
  `BASE64` longblob NOT NULL,
  `NOME` varchar(45)  NOT NULL,
  `DATA_CRIACAO` date NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_DOC_VISITA_EVENT_idx` (`ID_VISITA_EVENTO`),
  CONSTRAINT `FK_DOC_VISITA_EVENT` FOREIGN KEY (`ID_VISITA_EVENTO`) REFERENCES `VISITA_EVENTO` (`ID`)
);

CREATE TABLE `AGENDAMENTO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_PACIENTE` bigint NOT NULL,
  `ID_RESPONSAVEL` bigint NOT NULL,
  `DATA_HORA` datetime NOT NULL,
  `ANOTACOES` varchar(200) DEFAULT NULL,
  `SITUACAO` varchar(45) NOT NULL,
  `DATA_CRIACAO` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AGENDA_PACIENTE_idx` (`ID_PACIENTE`),
  KEY `FK_AGENDA_RESPONS_idx` (`ID_RESPONSAVEL`),
  CONSTRAINT `FK_AGENDA_PACIENTE` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `PACIENTE` (`ID`),
  CONSTRAINT `FK_AGENDA_RESPONS` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`)
);

CREATE TABLE `AGENDA_CONFIRMACAO` (
  `ID` varchar(100) NOT NULL,
  `SITUACAO` varchar(45) NOT NULL,
  `DATA_HORA_RESP` datetime NOT NULL,
  `IP_RESPOSTA` varchar(45) NOT NULL,
  `ID_PACIENTE` bigint NOT NULL,
  `ID_RESPONSAVEL` bigint NOT NULL,
  `DATA_CRIACAO` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_AG_CONF_PAC_idx` (`ID_PACIENTE`),
  KEY `FK_AG_CONF_RESP_idx` (`ID_RESPONSAVEL`),
  CONSTRAINT `FK_AG_CONF_PAC` FOREIGN KEY (`ID_PACIENTE`) REFERENCES `PACIENTE` (`ID`),
  CONSTRAINT `FK_AG_CONF_RESP` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`)
);

CREATE TABLE `INSTITUTO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CGC` varchar(16) NOT NULL,
  `CNES` varchar(45) DEFAULT NULL,
  `NOME` varchar(100) NOT NULL,
  `LOGO` longblob,
  `NOME_CORPORATIVO` varchar(100) NOT NULL,
  `NATUREZA_LEGAL` varchar(80) DEFAULT NULL,
  `LOGRADOURO` varchar(100) NOT NULL,
  `NUMERO` varchar(8) NOT NULL,
  `COMPLEMENTO` varchar(45) DEFAULT NULL,
  `CEP` varchar(8) NOT NULL,
  `ESTADO` varchar(45) NOT NULL,
  `BAIRRO` varchar(50) NOT NULL,
  `CIDADE` varchar(80) NOT NULL,
  `TELEFONE` varchar(45) NOT NULL,
  `DEPENDENCIA` varchar(45) DEFAULT NULL,
  `TIPO_DE_INSTITUICAO` varchar(45) DEFAULT NULL,
  `GESTOR` varchar(80) DEFAULT NULL,
  `TELEFONE_GESTOR` varchar(45) DEFAULT NULL,
  `EMAIL_GESTOR` varchar(80) DEFAULT NULL,
  `DATA_DE_REGISTRO` date DEFAULT NULL,
  `USUARIO_DE_REGISTRO` varchar(80) DEFAULT NULL,
  `CHAVE_ACESSO` varchar(80) DEFAULT NULL,
  `DATA_INICIO` datetime DEFAULT NULL,
  `DATA_FIM` datetime DEFAULT NULL,
  `CGC_TIPO` varchar(4) NOT NULL DEFAULT 'CNPJ',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CNPJ` (`CGC`),
  UNIQUE KEY `CHAVE_ACESSO_UNIQUE` (`CHAVE_ACESSO`)
);

CREATE TABLE `ANAMNESE_FORM` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `TITULO` varchar(200) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ANAMNESE_ITEM` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `PERGUNTA` varchar(2000) NOT NULL,
  `TIPO` varchar(45) NOT NULL DEFAULT 'string',
  `ID_ANAMNESE_FORM` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ANAMNESE_IT_FORM_idx` (`ID_ANAMNESE_FORM`),
  CONSTRAINT `FK_ANAMNESE_IT_FORM` FOREIGN KEY (`ID_ANAMNESE_FORM`) REFERENCES `ANAMNESE_FORM` (`ID`)
);

CREATE TABLE `UNIDADE_MEDIDA` (
  `ID` bigint NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  `TERMO` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PRESCRICAO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_VISITA` bigint NOT NULL,
  `ID_RESPONSAVEL` bigint NOT NULL,
  `DATA_INICIO` datetime NOT NULL,
  `DATA_FIM` datetime NOT NULL,
  `PRESCRICAO_ESPECIAL` varchar(1) DEFAULT 'N',
  `INSERE_EVENTO` varchar(1) DEFAULT 'N',
  `ID_RESPONSAVEL_CANCEL` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRESC_VISITA` (`ID_VISITA`),
  KEY `FK_PRESC_RESP` (`ID_RESPONSAVEL`),
  CONSTRAINT `FK_PRESC_RESP` FOREIGN KEY (`ID_RESPONSAVEL`) REFERENCES `RESPONSAVEL` (`ID`),
  CONSTRAINT `FK_PRESC_VISITA` FOREIGN KEY (`ID_VISITA`) REFERENCES `VISITA` (`ID`)
);

CREATE TABLE `ITEM_PRESCRICAO` (
  `SEQUENCIAL` int NOT NULL,
  `ID_PRESCRICAO` bigint NOT NULL,
  `DESCRICAO` varchar(200) NOT NULL,
  `OBSERVACOES` varchar(200) DEFAULT NULL,
  `VIA_ADM` varchar(100) DEFAULT NULL,
  `DOSAGEM` decimal(10,2) DEFAULT NULL,
  `ID_UNIDADE_MEDIDA` bigint DEFAULT NULL,
  `INTERVALO` int NOT NULL,
  `TIPO_INTERVALO` varchar(50) NOT NULL,
  PRIMARY KEY (`SEQUENCIAL`,`ID_PRESCRICAO`) USING BTREE,
  KEY `FK_ITEMPRESC_PRESC` (`ID_PRESCRICAO`),
  KEY `FK_ITEMPRESC_UNIMED` (`ID_UNIDADE_MEDIDA`),
  CONSTRAINT `FK_ITEMPRESC_PRESC` FOREIGN KEY (`ID_PRESCRICAO`) REFERENCES `PRESCRICAO` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `FK_ITEMPRESC_UNIMED` FOREIGN KEY (`ID_UNIDADE_MEDIDA`) REFERENCES `UNIDADE_MEDIDA` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE `EVOLUCAO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_VISITA` bigint NOT NULL,
  `DESCRICAO` varchar(5000) NOT NULL,
  `DH_EVOLUCAO` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EVOLUCAO_VISITA` (`ID_VISITA`),
  CONSTRAINT `FK_EVOLUCAO_VISITA` FOREIGN KEY (`ID_VISITA`) REFERENCES `VISITA` (`ID`)
);

CREATE TABLE `APP_PARAM` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ALIAS` varchar(100) NOT NULL,
  `NOME` varchar(80) NOT NULL,
  `GRUPO` varchar(45) NOT NULL,
  `TIPO` varchar(45) NOT NULL,
  `VALOR` varchar(1000) DEFAULT NULL,
  `VALORES_DE_GRUPO` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `APP_PARAM_ALIAS_UK` (`ALIAS`) USING BTREE
);

CREATE TABLE `TABELA_CBO` (
  `ID` bigint NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `DESCRICAO_UNIQUE` (`DESCRICAO`)
);

CREATE TABLE `ALERGIA` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`,`DESCRICAO`),
  UNIQUE KEY `DESCRICAO_UNIQUE` (`DESCRICAO`)
);

CREATE TABLE `NIV_PRE_CLIENTE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME_CLINICA` varchar(200) NOT NULL,
  `NOME_GESTOR` varchar(200) NOT NULL,
  `TIPO_CGC` varchar(4) NOT NULL,
  `CGC` varchar(16) NOT NULL,
  `EMAIL` varchar(200) NOT NULL,
  `TELEFONE_PRINCIPAL` varchar(30) NOT NULL,
  `UUID` varchar(50) NOT NULL,
  `DH_CONFIRMACAO` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `LAYOUT_RELATORIO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `DESCRICAO` varchar(200) NOT NULL,
  `XML` longblob,
  `DATA` date NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PARAMETROS_LAYOUT_RELATORIO` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_LAYOUT_RELATORIO` bigint NOT NULL,
  `NOME` varchar(200) NOT NULL,
  `TIPO` varchar(200) NOT NULL,
  `DESCRICAO` varchar(200) DEFAULT NULL,
  `VALOR_PADRAO` varchar(5000) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_CONTRAINT` (`ID_LAYOUT_RELATORIO`,`NOME`),
  KEY `FK_LAYOUT` (`ID_LAYOUT_RELATORIO`),
  CONSTRAINT `FK_LAYOUT` FOREIGN KEY (`ID_LAYOUT_RELATORIO`) REFERENCES `LAYOUT_RELATORIO` (`ID`)
);

CREATE TABLE `ANAMNESE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_VISITA` bigint NOT NULL,
  `RESPOSTA` varchar(5000) NOT NULL,
  `PERGUNTA` varchar(1000) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `fk_ANAMNESE_VISIT_idx` (`ID_VISITA`),
  CONSTRAINT `fk_ANAMNESE_VISIT` FOREIGN KEY (`ID_VISITA`) REFERENCES `VISITA` (`ID`)
);

CREATE TABLE `FORMULARIO_RESPONDIDO` (
  `ID` bigint NOT NULL,
  `ID_USUARIO` bigint NOT NULL,
  `ID_VISITA` bigint NOT NULL,
  `QUESTAO` varchar(4000) NOT NULL,
  `RESPOSTA` varchar(4000) NOT NULL,
  PRIMARY KEY (`ID`)
);