CREATE TABLE `FORNECEDOR` (
  `ID` VARCHAR(50) NOT NULL,
  `CPF_CNPJ` varchar(16) NOT NULL,
  `NOME_FANTASIA` varchar(120)  NOT NULL,
  `RAZAO_SOCIAL` varchar(120) NOT NULL,
  `INSCRICAO_ESTADUAL` varchar(40) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(40) DEFAULT NULL,
  `TIPO` varchar(80) NOT NULL,
  `OBSERVACAO` varchar(800) DEFAULT NULL,
  `TELEFONE_PRINCIPAL` varchar(30) NOT NULL,
  `TELEFONE_SECUNDARIO` varchar(30) DEFAULT NULL,
  `EMAIL` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `CPF_CNPJ_UNIQUE` (`CPF_CNPJ`)
);

CREATE TABLE `ENDERECO_FORNECEDOR` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `ID_FORNECEDOR` bigint NOT NULL,
  `LOGRADOURO` varchar(200) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  `COMPLEMENTO` varchar(50) DEFAULT NULL,
  `CODIGO_POSTAL` varchar(8) DEFAULT NULL,
  `ESTADO` varchar(2) DEFAULT NULL,
  `BAIRRO` varchar(100) DEFAULT NULL,
  `CIDADE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_FORNECEDOR_UNIQUE` (`ID_FORNECEDOR`),
  KEY `FK_ENDERECO_FORNECEDOR_idx` (`ID_FORNECEDOR`),
  CONSTRAINT `FK_ENDERECO_FORNECEDOR` FOREIGN KEY (`ID_FORNECEDOR`) REFERENCES `FORNECEDOR` (`ID`)
);