CREATE TABLE `LEMBRETE` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DH_CRIACAO` date DEFAULT NULL,
  `DESCRICAO` varchar(200) DEFAULT NULL,
  `ID_USUARIO` bigint NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_LEMBRETE_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIO` (`ID`)
);